site_name: SuPOrdnung
nav:
  - SOP Bsc Informatik 2014:
    - Studien- und Prüfungsordnung: sop_bsc_inf_2014.md
  - SOP Bsc Informatik 2023:
    - Studien- und Prüfungsordnung: sop_bsc_inf_2023.md
    - Module: mods.md
theme: readthedocs
extra_css:
  - extra.css
markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      anchorlink: true
      baselevel: 1
      toc_depth: 2
  - tables
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
