site_name: Inoffizielle Studien- und Prüfungsordnung der FU-Berlin
nav:
  - index.md
  - Rahmenstudien- und -prüfungsordnung: rspo_2013.md
  - Informatik Bsc 2014:
    - Studien- und Prüfungsordnung: inf_bsc_2014_sop.md
    - Modulbeschreibungen:
      - inf_bsc_2014_modules/Algorithmen, Datenstrukturen und Datenabstraktion.md
      - inf_bsc_2014_modules/Analysis für Informatik.md
      - inf_bsc_2014_modules/Arbeits- und Lebensmethodik.md
      - inf_bsc_2014_modules/Auswirkungen der Informatik.md
      - inf_bsc_2014_modules/Basisdidaktik Informatik.md
      - inf_bsc_2014_modules/Berufsbezogenes Praktikum Informatik.md
      - inf_bsc_2014_modules/Datenbanksysteme.md
      - inf_bsc_2014_modules/Existenzgründung in der IT-Industrie.md
      - inf_bsc_2014_modules/Forschungspraktikum.md
      - inf_bsc_2014_modules/Funktionale Programmierung.md
      - inf_bsc_2014_modules/Gesellschaftliche Aspekte der Informatik.md
      - inf_bsc_2014_modules/Grundlagen der Technischen Informatik.md
      - inf_bsc_2014_modules/Grundlagen der Theoretischen Informatik.md
      - inf_bsc_2014_modules/Grundlagen des Managements von IT-Projekten.md
      - inf_bsc_2014_modules/Lineare Algebra für Informatik.md
      - inf_bsc_2014_modules/Logik und Diskrete Mathematik.md
      - inf_bsc_2014_modules/Nichtsequentielle und verteilte Programmierung.md
      - inf_bsc_2014_modules/Objektorientierte Programmierung für Studentinnen und Studenten mit Programmierkenntnissen.md
      - inf_bsc_2014_modules/Objektorientierte Programmierung für Studentinnen und Studenten ohne Programmierkenntnisse.md
      - inf_bsc_2014_modules/Planung, Durchführung und Analyse eines Tutoriums in der Informatik.md
      - inf_bsc_2014_modules/Rechnerarchitektur, Betriebs- und Kommunikationssysteme.md
      - inf_bsc_2014_modules/Rechtliche Aspekte der Informatik.md
      - inf_bsc_2014_modules/Softwareprojekt A.md
      - inf_bsc_2014_modules/Softwareprojekt B.md
      - inf_bsc_2014_modules/Softwaretechnik.md
      - inf_bsc_2014_modules/Systemverwaltung.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten Praktische Informatik.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten Technische Informatik.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten Theoretische Informatik.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten in der Informatik.md
  - Informatik Bsc 2023:
    - Studien- und Prüfungsordnung: inf_bsc_2023_sop.md
    - Modulbeschreibungen:
      - inf_bsc_2023_modules/Aktuelle Themen in der Informatik.md
      - inf_bsc_2023_modules/Algorithmen und Datenstrukturen.md
      - inf_bsc_2023_modules/Analysis für Informatik.md
      - inf_bsc_2023_modules/Angewandte Biometrie.md
      - inf_bsc_2023_modules/Arbeits- und Lebensmethodik.md
      - inf_bsc_2023_modules/Architektur eingebetteter Systeme.md
      - inf_bsc_2023_modules/Auswirkungen der Informatik.md
      - inf_bsc_2023_modules/Berufsbezogenes Praktikum Informatik.md
      - inf_bsc_2023_modules/Betriebs- und Kommunikationssysteme.md
      - inf_bsc_2023_modules/Datenbanksysteme.md
      - inf_bsc_2023_modules/Datenvisualisierung.md
      - inf_bsc_2023_modules/Diskrete Strukturen für Informatik.md
      - inf_bsc_2023_modules/Forschungspraktikum.md
      - inf_bsc_2023_modules/Funktionale Programmierung.md
      - inf_bsc_2023_modules/Gender and Diversity.md
      - inf_bsc_2023_modules/Grundlagen der Theoretischen Informatik.md
      - inf_bsc_2023_modules/Grundlagen des Datenschutzrechts.md
      - inf_bsc_2023_modules/Informationssicherheit.md
      - inf_bsc_2023_modules/Informationstheorie.md
      - inf_bsc_2023_modules/Konzepte der Programmierung.md
      - inf_bsc_2023_modules/Lineare Algebra für Informatik.md
      - inf_bsc_2023_modules/Maschinelles Lernen.md
      - inf_bsc_2023_modules/Mensch-Computer Interaktion.md
      - inf_bsc_2023_modules/Nebenläufige, parallele und verteilte Programmierung.md
      - inf_bsc_2023_modules/Planung, Durchführung und Evaluation eines Tutoriums in der Informatik.md
      - inf_bsc_2023_modules/Praktiken professioneller Softwareentwicklung.md
      - inf_bsc_2023_modules/Programmierpraktikum.md
      - inf_bsc_2023_modules/Projektmanagement in agilen Umgebungen.md
      - inf_bsc_2023_modules/Rechnerarchitektur.md
      - inf_bsc_2023_modules/Softwareprojekt.md
      - inf_bsc_2023_modules/Softwaretechnik.md
      - inf_bsc_2023_modules/Statistik für Informatik.md
      - inf_bsc_2023_modules/Systemverwaltung.md
      - inf_bsc_2023_modules/Vertiefte Aspekte der Informatik.md
      - inf_bsc_2023_modules/Vertiefung Theoretische Informatik.md
      - inf_bsc_2023_modules/Wissenschaftliches Arbeiten in der Informatik.md
  - Informatik Msc 2014:
    - Studien- und Prüfungsordnung: inf_msc_2014_sop.md
    - Modulebeschreibungen:
      - inf_msc_2014_modules/Verteilte Systeme.md
      - inf_msc_2014_modules/Medizinische Bildverarbeitung.md
      - inf_msc_2014_modules/Modellgetriebene Softwareentwicklung.md
      - inf_msc_2014_modules/Softwareprojekt – Theoretische Informatik A.md
      - inf_msc_2014_modules/Netzbasierte Informationssysteme.md
      - inf_msc_2014_modules/Wissenschaftliches Arbeiten Technische Informatik A.md
      - inf_msc_2014_modules/Mobilkommunikation.md
      - inf_msc_2014_modules/Softwareprojekt – Praktische Informatik A.md
      - inf_msc_2014_modules/Semantik von Programmiersprachen.md
      - inf_msc_2014_modules/Praktiken professioneller Softwareentwicklung.md
      - inf_msc_2014_modules/Projektmanagement – Vertiefung.md
      - inf_msc_2014_modules/Wissenschaftliches Arbeiten Praktische Informatik B.md
      - inf_msc_2014_modules/XML-Technologien.md
      - inf_msc_2014_modules/Spezielle Aspekte der Theoretischen Informatik.md
      - inf_msc_2014_modules/Bildverarbeitung.md
      - inf_msc_2014_modules/Ausgewählte Themen der Technischen Informatik.md
      - inf_msc_2014_modules/Fortgeschrittene Themen der Theoretischen Informatik.md
      - inf_msc_2014_modules/Höhere Algorithmik.md
      - inf_msc_2014_modules/Betriebssysteme.md
      - inf_msc_2014_modules/Aktuelle Forschungsthemen der Theoretischen Informatik.md
      - inf_msc_2014_modules/Grundlagen des Softwaretestens.md
      - inf_msc_2014_modules/Aktuelle Forschungsthemen der Praktischen Informatik.md
      - inf_msc_2014_modules/Wissenschaftliches Arbeiten Theoretische Informatik A.md
      - inf_msc_2014_modules/Rechnersicherheit.md
      - inf_msc_2014_modules/Softwareprozesse.md
      - inf_msc_2014_modules/Robotik.md
      - inf_msc_2014_modules/Softwareprojekt – Technische Informatik B.md
      - inf_msc_2014_modules/Künstliche Intelligenz.md
      - inf_msc_2014_modules/Kryptographie und Sicherheit in Verteilten Systemen.md
      - inf_msc_2014_modules/Datenbanktechnologie.md
      - inf_msc_2014_modules/Softwareprojekt – Praktische Informatik B.md
      - inf_msc_2014_modules/Projektmanagement.md
      - inf_msc_2014_modules/Spezielle Aspekte der Technischen Informatik.md
      - inf_msc_2014_modules/Semantisches Geschäftsprozessmanagement.md
      - inf_msc_2014_modules/Ausgewählte Themen der Theoretischen Informatik.md
      - inf_msc_2014_modules/Wissenschaftliches Arbeiten Technische Informatik B.md
      - inf_msc_2014_modules/Spezielle Aspekte der Datenverwaltung.md
      - inf_msc_2014_modules/Mustererkennung.md
      - inf_msc_2014_modules/Algorithmische Geometrie.md
      - inf_msc_2014_modules/Softwareprojekt – Theoretische Informatik B.md
      - inf_msc_2014_modules/Computer-Vision.md
      - inf_msc_2014_modules/Modelchecking.md
      - inf_msc_2014_modules/Telematik.md
      - inf_msc_2014_modules/Spezielle Aspekte der Softwareentwicklung.md
      - inf_msc_2014_modules/Aktuelle Forschungsthemen der Technischen Informatik.md
      - inf_msc_2014_modules/Softwareprojekt – Technische Informatik A.md
      - inf_msc_2014_modules/Ausgewählte Themen der Praktischen Informatik.md
      - inf_msc_2014_modules/Wissenschaftliches Arbeiten Theoretische Informatik B.md
      - inf_msc_2014_modules/Mikroprozessor-Praktikum.md
      - inf_msc_2014_modules/Computergrafik.md
      - inf_msc_2014_modules/Wissenschaftliches Arbeiten Praktische Informatik A.md
      - inf_msc_2014_modules/Übersetzerbau.md
      - inf_msc_2014_modules/Empirische Bewertung in der Informatik.md
      - inf_msc_2014_modules/Spezielle Aspekte der Praktischen Informatik.md
  - Bioinformatik Bsc 2012:
    - Studien- und Prüfungsordnung: bioinf_bsc_2012_sop.md
    - Modulbeschreibungen:
      - bioinf_bsc_2012_modules/Algorithmen und Datenstrukturen – Praktikum.md
      - bioinf_bsc_2012_modules/Algorithmen und Datenstrukturen.md
      - bioinf_bsc_2012_modules/Algorithmische Bioinformatik.md
      - bioinf_bsc_2012_modules/Allgemeine Biologie.md
      - bioinf_bsc_2012_modules/Allgemeine Chemie.md
      - bioinf_bsc_2012_modules/Bildverarbeitung.md
      - bioinf_bsc_2012_modules/Computer-Vision.md
      - bioinf_bsc_2012_modules/Computergrafik.md
      - bioinf_bsc_2012_modules/Datenbanktechnologie.md
      - bioinf_bsc_2012_modules/Empirische Bewertung in der Informatik.md
      - bioinf_bsc_2012_modules/Genetik und Genomforschung.md
      - bioinf_bsc_2012_modules/Grundlagen des Softwaretestens.md
      - bioinf_bsc_2012_modules/Künstliche Intelligenz.md
      - bioinf_bsc_2012_modules/Mathematik für Bioinformatiker I.md
      - bioinf_bsc_2012_modules/Mathematik für Bioinformatiker II.md
      - bioinf_bsc_2012_modules/Medizinische Bildverarbeitung.md
      - bioinf_bsc_2012_modules/Medizinische Physiologie.md
      - bioinf_bsc_2012_modules/Modellgetriebene Softwareentwicklung.md
      - bioinf_bsc_2012_modules/Molekularbiologie und Biochemie I.md
      - bioinf_bsc_2012_modules/Molekularbiologie und Biochemie II.md
      - bioinf_bsc_2012_modules/Molekularbiologie und Biochemie III.md
      - bioinf_bsc_2012_modules/Mustererkennung.md
      - bioinf_bsc_2012_modules/Netzbasierte Informationssysteme.md
      - bioinf_bsc_2012_modules/Neurobiologie.md
      - bioinf_bsc_2012_modules/Projektmanagement im Softwarebereich.md
      - bioinf_bsc_2012_modules/Projektmanagement – Vertiefung.md
      - bioinf_bsc_2012_modules/Projektmanagement.md
      - bioinf_bsc_2012_modules/Rechnersicherheit.md
      - bioinf_bsc_2012_modules/Semantisches Geschäftsprozessmanagement.md
      - bioinf_bsc_2012_modules/Softwareprozesse.md
      - bioinf_bsc_2012_modules/Statistik für Biowissenschaften I.md
      - bioinf_bsc_2012_modules/Statistik für Biowissenschaften II.md
      - bioinf_bsc_2012_modules/Übersetzerbau.md
  - Bioinformatik Msc 2019:
    - Studien- und Prüfungsordnung: bioinf_msc_2019_sop.md
    - Modulbeschreibungen:
      - bioinf_msc_2019_modules/Advanced Algorithms for Bioinformatics.md
      - bioinf_msc_2019_modules/Advanced Biometrical Methods.md
      - bioinf_msc_2019_modules/Advanced Network Analysis.md
      - bioinf_msc_2019_modules/Applied Machine Learning in Bioinformatics.md
      - bioinf_msc_2019_modules/Applied Sequence Analysis.md
      - bioinf_msc_2019_modules/Big Data Analysis in Bioinformatics.md
      - bioinf_msc_2019_modules/Biodiversity and Evolution.md
      - bioinf_msc_2019_modules/Complex Data Analysis in Physiology.md
      - bioinf_msc_2019_modules/Complex Systems in Bioinformatics.md
      - bioinf_msc_2019_modules/Complex Systems in Biomedical Applications.md
      - bioinf_msc_2019_modules/Computational Systems Biology.md
      - bioinf_msc_2019_modules/Computer-Aided Drug Design.md
      - bioinf_msc_2019_modules/Current research topics in Bioinformatics A.md
      - bioinf_msc_2019_modules/Current research topics in Bioinformatics B.md
      - bioinf_msc_2019_modules/Current research topics in Bioinformatics C.md
      - bioinf_msc_2019_modules/Current topics in cell-physiology.md
      - bioinf_msc_2019_modules/Current topics in medical genomics.md
      - bioinf_msc_2019_modules/Current topics in structural bioinformatics.md
      - bioinf_msc_2019_modules/Environmental metagenomics.md
      - bioinf_msc_2019_modules/Ethics and Policy Questions.md
      - bioinf_msc_2019_modules/Foundations in Bio-Medicine.md
      - bioinf_msc_2019_modules/Foundations in Computer Science.md
      - bioinf_msc_2019_modules/Foundations in Mathematics and Statistics.md
      - bioinf_msc_2019_modules/Human Evolution.md
      - bioinf_msc_2019_modules/Introduction to Focus Areas.md
      - bioinf_msc_2019_modules/Machine Learning in Bioinformatics.md
      - bioinf_msc_2019_modules/Medical Bioinformatics.md
      - bioinf_msc_2019_modules/Methodology for clinical trials.md
      - bioinf_msc_2019_modules/Methods in Life Sciences.md
      - bioinf_msc_2019_modules/Research Internship.md
      - bioinf_msc_2019_modules/Selected topics in Bioinformatics A.md
      - bioinf_msc_2019_modules/Selected topics in Bioinformatics B.md
      - bioinf_msc_2019_modules/Special aspects of Bioinformatics A.md
      - bioinf_msc_2019_modules/Special aspects of Bioinformatics B.md
      - bioinf_msc_2019_modules/Special aspects of Bioinformatics C.md
      - bioinf_msc_2019_modules/Structural Bioinformatics.md
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share

repo_url: https://github.com/SGSSGene/FUB-SuP-Ordnung
extra_css:
  - extra.css
markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      anchorlink: true
      baselevel: 1
      toc_depth: 4
  - tables
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
