site_name: SuPOrdnung
nav:
  - Home: index.md
  - SOP Bsc Informatik 2014:
    - Studien- und Prüfungsordnung: sop_bsc_inf_2014.md
    - Modulbeschreibungen:
      - inf_bsc_2014_modules/Algorithmen, Datenstrukturen und Datenabstraktion.md
      - inf_bsc_2014_modules/Analysis für Informatik.md
      - inf_bsc_2014_modules/Arbeits- und Lebensmethodik.md
      - inf_bsc_2014_modules/Auswirkungen der Informatik.md
      - inf_bsc_2014_modules/Basisdidaktik Informatik.md
      - inf_bsc_2014_modules/Berufsbezogenes Praktikum Informatik.md
      - inf_bsc_2014_modules/Datenbanksysteme.md
      - inf_bsc_2014_modules/Existenzgründung in der IT-Industrie.md
      - inf_bsc_2014_modules/Forschungspraktikum.md
      - inf_bsc_2014_modules/Funktionale Programmierung.md
      - inf_bsc_2014_modules/Gesellschaftliche Aspekte der Informatik.md
      - inf_bsc_2014_modules/Grundlagen der Technischen Informatik.md
      - inf_bsc_2014_modules/Grundlagen der Theoretischen Informatik.md
      - inf_bsc_2014_modules/Grundlagen des Managements von IT-Projekten.md
      - inf_bsc_2014_modules/Lineare Algebra für Informatik.md
      - inf_bsc_2014_modules/Logik und Diskrete Mathematik.md
      - inf_bsc_2014_modules/Nichtsequentielle und verteilte Programmierung.md
      - inf_bsc_2014_modules/Objektorientierte Programmierung für Studentinnen und Studenten mit Programmierkenntnissen.md
      - inf_bsc_2014_modules/Objektorientierte Programmierung für Studentinnen und Studenten ohne Programmierkenntnisse.md
      - inf_bsc_2014_modules/Planung, Durchführung und Analyse eines Tutoriums in der Informatik.md
      - inf_bsc_2014_modules/Rechnerarchitektur, Betriebs- und Kommunikationssysteme.md
      - inf_bsc_2014_modules/Rechtliche Aspekte der Informatik.md
      - inf_bsc_2014_modules/Softwareprojekt A.md
      - inf_bsc_2014_modules/Softwareprojekt B.md
      - inf_bsc_2014_modules/Softwaretechnik.md
      - inf_bsc_2014_modules/Systemverwaltung.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten Praktische Informatik.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten Technische Informatik.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten Theoretische Informatik.md
      - inf_bsc_2014_modules/Wissenschaftliches Arbeiten in der Informatik.md
  - SOP Bsc Informatik 2023:
    - Studien- und Prüfungsordnung: sop_bsc_inf_2023.md
    - Modulbeschreibungen:
      - inf_bsc_2023_modules/Aktuelle Themen in der Informatik.md
      - inf_bsc_2023_modules/Algorithmen und Datenstrukturen.md
      - inf_bsc_2023_modules/Analysis für Informatik.md
      - inf_bsc_2023_modules/Angewandte Biometrie.md
      - inf_bsc_2023_modules/Arbeits- und Lebensmethodik.md
      - inf_bsc_2023_modules/Architektur eingebetteter Systeme.md
      - inf_bsc_2023_modules/Auswirkungen der Informatik.md
      - inf_bsc_2023_modules/Berufsbezogenes Praktikum Informatik.md
      - inf_bsc_2023_modules/Betriebs- und Kommunikationssysteme.md
      - inf_bsc_2023_modules/Datenbanksysteme.md
      - inf_bsc_2023_modules/Datenvisualisierung.md
      - inf_bsc_2023_modules/Diskrete Strukturen für Informatik.md
      - inf_bsc_2023_modules/Forschungspraktikum.md
      - inf_bsc_2023_modules/Funktionale Programmierung.md
      - inf_bsc_2023_modules/Gender and Diversity.md
      - inf_bsc_2023_modules/Grundlagen der Theoretischen Informatik.md
      - inf_bsc_2023_modules/Grundlagen des Datenschutzrechts.md
      - inf_bsc_2023_modules/Informationssicherheit.md
      - inf_bsc_2023_modules/Informationstheorie.md
      - inf_bsc_2023_modules/Konzepte der Programmierung.md
      - inf_bsc_2023_modules/Lineare Algebra für Informatik.md
      - inf_bsc_2023_modules/Maschinelles Lernen.md
      - inf_bsc_2023_modules/Mensch-Computer Interaktion.md
      - inf_bsc_2023_modules/Nebenläufige, parallele und verteilte Programmierung.md
      - inf_bsc_2023_modules/Planung, Durchführung und Evaluation eines Tutoriums in der Informatik.md
      - inf_bsc_2023_modules/Praktiken professioneller Softwareentwicklung.md
      - inf_bsc_2023_modules/Programmierpraktikum.md
      - inf_bsc_2023_modules/Projektmanagement in agilen Umgebungen.md
      - inf_bsc_2023_modules/Rechnerarchitektur.md
      - inf_bsc_2023_modules/Softwareprojekt.md
      - inf_bsc_2023_modules/Softwaretechnik.md
      - inf_bsc_2023_modules/Statistik für Informatik.md
      - inf_bsc_2023_modules/Systemverwaltung.md
      - inf_bsc_2023_modules/Vertiefte Aspekte der Informatik.md
      - inf_bsc_2023_modules/Vertiefung Theoretische Informatik.md
      - inf_bsc_2023_modules/Wissenschaftliches Arbeiten in der Informatik.md
theme: readthedocs
repo_url: https://github.com/SGSSGene/FUB-SuP-Ordnung
extra_css:
  - extra.css
markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      anchorlink: true
      baselevel: 1
      toc_depth: 2
  - tables
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
